### ISSUE TITLE
SNMPSET usage

### ISSUE THREAD

**Issue by EngKhaled91** [delimitry/snmp-server#12]
Hello Everybody:
I started the server successfully and write my config file and I had no problems.
but when I tried to send snmpset command to OID specified in config file I got the following error:
![image](https://user-images.githubusercontent.com/29969831/61133666-8f874e80-a4c6-11e9-9a98-39513d48b765.png)
I tried to change community with no effects
the command I used is:
snmpset -v2c -c private 127.0.0.1:1235 (OID) s "newValue"
Is there any possible solutions?
or snmpset is not supported in the snmp simulator?
thanks for responding

**Comment by delimitry** [comment]
Hi @EngKhaled91, yes current version of **snmp-server** doesn't support snmp set command, but it's possible to add it.

**Comment by EngKhaled91** [comment]
Thanks @delimitry, 
Is there any quick steps can I do to add it to the code?

**Comment by delimitry** [comment]
@EngKhaled91 I've added snmp set support, please check it.

**Comment by EngKhaled91** [comment]
Thanks alot put I'll put a problem that happened when using snmpset:
![image](https://user-images.githubusercontent.com/29969831/61223059-98755b80-a724-11e9-9e07-729dc76200d8.png)
and I solved it adding the following line to your code:
![image](https://user-images.githubusercontent.com/29969831/61223119-b5aa2a00-a724-11e9-86bb-232dcccb8e79.png)
and this worked for me.
I want to thank you for your time to help me.
