### ISSUE TITLE
Gauge32 does not accept numbers between 15 and 16 bits. 

### ISSUE THREAD

**Issue by WorksWellWithOthers** [delimitry/snmp-server#23]
It seems that the OIDS with Gauge32 does not like numbers between 32768 and 65535.
I'm assuming this is a user error and I'm feeding it incorrectly and am wondering how to do it right. 

snmpset -v2c -c community_name host:port MIB::someName.1 'u' 40000

returns max value

**Comment by delimitry** [comment]
Thank you @WorksWellWithOthers! :+1: 
I've fixed this error. Now it returns correct value:
```
$ snmpset -v2c -c public 0.0.0.0:161 .1.3.6.1.4.1.1.4.0 u 40000
iso.3.6.1.4.1.1.4.0 = Gauge32: 40000
```

**Comment by WorksWellWithOthers** [comment]
I'm looking forward to checking out the changes. I wanted to do it myself but failed.
I think a similar thing was happening with 'i'. 

Also, I wasn't sure if Gauge32 was supposed to wrap or not. 
Sorry that I can't be of more help. Snmp hard.

**Comment by delimitry** [comment]
@WorksWellWithOthers I've checked 'i', and found a problem there too and fixed it.
