### ISSUE TITLE
Add support for value ranges / enumeration

### ISSUE THREAD

**Issue by DavidVentura** [delimitry/snmp-server#27]
Hi
Certain OIDs only support a range of values (IF-MIB::ifAdminStatus) / enumeration, and when trying to `set` them with a value outside the supported values, it should fail with `wrongValue`.

Is it possible to add support for this?

**Comment by delimitry** [comment]
Hi @DavidVentura, yes it is possible to add this feature. 
I'll add it soon. Thank you! :+1:

**Comment by delimitry** [comment]
@DavidVentura I've added enum support for INTEGER type.

To use it add enum with allowed values to integer type in your config file:
```
    '1.3.6......0': integer(1, enum=[1, 2, 3]),
```
And it will fail with `wrongValue` error on `snmpset` with value outside the range of enum values.
```
$ snmpset -v2c -c public IP:161 .1.3.6......0 i 4
Reason: wrongValue (The set value is illegal or unsupported in some way)
```
But if the value is in range, it will set it successfully:
```
$ snmpset -v2c -c public IP:161 .1.3.6......0 i 2
iso.3.6.1......0 = INTEGER: 2
```
