### ISSUE TITLE
Stuck in a loop walking OIDs

### ISSUE THREAD

**Issue by devuxnullux** [delimitry/snmp-server#42]
Hi, I'm using your tools on a project of mine, I found it exceptional for tinkering with snmp, what and excellent tool

and  depending on the data I put in the config, snmpwalk keep drilling down past the OIDs in the config

here an exemple of a non working config

```
## CONF

def my_response(oid):
	res = '|'.join(oid.split('.'))
	return octet_string('response: {}'.format(res))


DATA = {
  '.1.3.6.1.4.1.2021.9.1.1.1': integer(1),
  '.1.3.6.1.4.1.2021.9.1.2.1': octet_string('/'),
  '.1.3.6.1.4.1.2021.9.1.3.1': octet_string('/dev/sda2'),
  '.1.3.6.1.4.1.2021.9.1.4.1': integer(-1),
  '.1.3.6.1.4.1.2021.9.1.5.1': integer(10),
  '.1.3.6.1.4.1.2021.9.1.6.1': integer(40970464),
  '.1.3.6.1.4.1.2021.9.1.7.1': integer(23622920),
  '.1.3.6.1.4.1.2021.9.1.8.1': integer(15234164),
  '.1.3.6.1.4.1.2021.9.1.9.1': integer(37),
  '.1.3.6.1.4.1.2021.9.1.10.1': integer(6),
  '.1.3.6.1.4.1.2021.9.1.11.1': integer(40970464),
  '.1.3.6.1.4.1.2021.9.1.12.1': integer(0),
  '.1.3.6.1.4.1.2021.9.1.13.1': integer(23622920),
  '.1.3.6.1.4.1.2021.9.1.14.1': integer(0),
  '.1.3.6.1.4.1.2021.9.1.15.1': integer(15234164),
  '.1.3.6.1.4.1.2021.9.1.16.1': integer(0),
  '.1.3.6.1.4.1.2021.9.1.100.1': integer(0),
  '.1.3.6.1.4.1.2021.9.1.101.1': octet_string(''),
  '.1.3.6.1.4.1.2021.10.1.1.1': integer(1),
}

## END OF CONF
```

and the output of snmpwalk :
```
snmpwalk -v 2c -c c  127.0.0.1:1610 .
iso.3.6.1.4.1.2021.9.1.1.1 = INTEGER: 1
iso.3.6.1.4.1.2021.9.1.2.1 = STRING: "/"
iso.3.6.1.4.1.2021.9.1.3.1 = STRING: "/dev/sda2"
iso.3.6.1.4.1.2021.9.1.4.1 = INTEGER: -1
iso.3.6.1.4.1.2021.9.1.5.1 = INTEGER: 10
iso.3.6.1.4.1.2021.9.1.6.1 = INTEGER: 40970464
iso.3.6.1.4.1.2021.9.1.7.1 = INTEGER: 23622920
iso.3.6.1.4.1.2021.9.1.8.1 = INTEGER: 15234164
iso.3.6.1.4.1.2021.9.1.9.1 = INTEGER: 37
iso.3.6.1.4.1.2021.9.1.10.1 = INTEGER: 6
iso.3.6.1.4.1.2021.9.1.11.1 = INTEGER: 40970464
iso.3.6.1.4.1.2021.9.1.12.1 = INTEGER: 0
iso.3.6.1.4.1.2021.9.1.13.1 = INTEGER: 23622920
iso.3.6.1.4.1.2021.9.1.14.1 = INTEGER: 0
iso.3.6.1.4.1.2021.9.1.15.1 = INTEGER: 15234164
iso.3.6.1.4.1.2021.9.1.16.1 = INTEGER: 0
iso.3.6.1.4.1.2021.9.1.100.1 = INTEGER: 0
iso.3.6.1.4.1.2021.9.1.101.1 = ""
iso.3.6.1.4.1.2021.10.1.1.1 = INTEGER: 1
iso.3.6.1.4.1.2021.10.1.2.1.0 = NULL
iso.3.6.1.4.1.2021.10.1.3.1.0 = NULL
iso.3.6.1.4.1.2021.10.1.4.1.0 = NULL
iso.3.6.1.4.1.2021.10.1.5.1.0 = NULL
iso.3.6.1.4.1.2021.10.1.6.1.0 = NULL
iso.3.6.1.4.1.2021.10.1.7.1.0 = NULL
iso.3.6.1.4.1.2021.10.1.8.1.0 = NULL
iso.3.6.1.4.1.2021.10.1.9.1.0 = NULL
iso.3.6.1.4.1.2021.10.1.10.1.0 = NULL
iso.3.6.1.4.1.2021.10.1.11.1.0 = NULL
iso.3.6.1.4.1.2021.10.1.12.1.0 = NULL
iso.3.6.1.4.1.2021.10.1.13.1.0 = NULL
iso.3.6.1.4.1.2021.10.1.14.1.0 = NULL
iso.3.6.1.4.1.2021.10.1.15.1.0 = NULL
iso.3.6.1.4.1.2021.10.1.16.1.0 = NULL
iso.3.6.1.4.1.2021.10.1.17.1.0 = NULL
iso.3.6.1.4.1.2021.10.1.18.1.0 = NULL
iso.3.6.1.4.1.2021.10.1.19.1.0 = NULL
iso.3.6.1.4.1.2021.10.1.20.1.0 = NULL
.........
```

and it goes like that forever
Is there anything that I can put on the config to end the mayhem ? 

BR

**Comment by delimitry** [comment]
Hi @devuxnullux! 
Thank you! 

I made a fix in "fix_loop" branch. 
Could you please check if it solves your problem: 
https://github.com/delimitry/snmp-server/blob/fix_loop/snmp-server.py

**Comment by devuxnullux** [comment]
Hello @delimitry, working like a charm,

resulting answer as expected 

iso.3.6.1.2.1.25.2.2.0 = INTEGER: 1024
iso.3.6.1.2.1.25.2.3.1.1.2 = INTEGER: 2
iso.3.6.1.2.1.25.2.3.1.1.31 = INTEGER: 31
iso.3.6.1.2.1.25.2.3.1.2.2 = STRING: "Virtual memory"
iso.3.6.1.2.1.25.2.3.1.2.31 = OID: iso.3.6.1.2.1.25.2.1.4
iso.3.6.1.2.1.25.2.3.1.3.2 = STRING: "Virtual memory"
iso.3.6.1.2.1.25.2.3.1.3.31 = STRING: "/"
iso.3.6.1.2.1.25.2.3.1.4.2 = INTEGER: 1024
iso.3.6.1.2.1.25.2.3.1.4.31 = INTEGER: 4096
iso.3.6.1.2.1.25.2.3.1.5.2 = INTEGER: 2048
iso.3.6.1.2.1.25.2.3.1.5.31 = INTEGER: 10242616
iso.3.6.1.2.1.25.2.3.1.6.2 = INTEGER: 1024
iso.3.6.1.2.1.25.2.3.1.6.31 = INTEGER: 3808541
iso.3.6.1.2.1.25.3.2.1.1.196608 = INTEGER: 196608
iso.3.6.1.2.1.25.3.2.1.1.196609 = INTEGER: 196609
iso.3.6.1.2.1.25.3.2.1.1.196610 = INTEGER: 196610
iso.3.6.1.2.1.25.3.2.1.1.196611 = INTEGER: 196611
iso.3.6.1.2.1.25.3.2.1.1.262145 = INTEGER: 262145
iso.3.6.1.2.1.25.3.2.1.1.262146 = INTEGER: 262146
iso.3.6.1.2.1.25.3.2.1.1.262147 = INTEGER: 262147
iso.3.6.1.2.1.25.3.2.1.1.786432 = INTEGER: 786432
iso.3.6.1.2.1.25.6.3.1.2 = STRING: "named"
iso.3.6.1.4.1.2021.9.1.1.1 = INTEGER: 1
iso.3.6.1.4.1.2021.9.1.2.1 = STRING: "/"
iso.3.6.1.4.1.2021.9.1.3.1 = STRING: "/dev/sda2"
iso.3.6.1.4.1.2021.9.1.4.1 = INTEGER: -1
iso.3.6.1.4.1.2021.9.1.5.1 = INTEGER: 10
iso.3.6.1.4.1.2021.9.1.6.1 = INTEGER: 40970464
iso.3.6.1.4.1.2021.9.1.7.1 = INTEGER: 23622920
iso.3.6.1.4.1.2021.9.1.8.1 = INTEGER: 15234164
iso.3.6.1.4.1.2021.9.1.9.1 = INTEGER: 37
iso.3.6.1.4.1.2021.9.1.10.1 = INTEGER: 6
iso.3.6.1.4.1.2021.9.1.11.1 = INTEGER: 40970464
iso.3.6.1.4.1.2021.9.1.12.1 = INTEGER: 0
iso.3.6.1.4.1.2021.9.1.13.1 = INTEGER: 23622920
iso.3.6.1.4.1.2021.9.1.14.1 = INTEGER: 0
iso.3.6.1.4.1.2021.9.1.15.1 = INTEGER: 15234164
iso.3.6.1.4.1.2021.9.1.16.1 = INTEGER: 0
iso.3.6.1.4.1.2021.9.1.100.1 = INTEGER: 0
iso.3.6.1.4.1.2021.9.1.101.1 = ""
iso.3.6.1.4.1.2021.10.1.1.1 = INTEGER: 1
iso.3.6.1.4.1.2021.10.1.2.1.0 = No more variables left in this MIB View (It is past the end of the MIB tree)

Thanks alot have a great day
BR

**Comment by devuxnullux** [comment]
Ooops,

Another loop seems to happen with this conf:

### START CONF

  '1.3.6.1.2.1.25.6.3.1.2': octet_string('named'),  # return a process value to avoid timeout
  '.1.3.6.1.2.1.25.2.3.1.1.31': integer(31),
 
  '.1.3.6.1.2.1.25.2.3.1.2.31': object_identifier('1.3.6.1.2.1.25.2.1.4'),
  '.1.3.6.1.2.1.25.2.3.1.3.31': octet_string('/'),
  '.1.3.6.1.2.1.25.2.3.1.4.31': integer(4096),
  '.1.3.6.1.2.1.25.2.3.1.5.31': integer(10242616),
  '.1.3.6.1.2.1.25.2.3.1.6.31': integer(3808541),

  '.1.3.6.1.2.1.25.3.2.1.1.196608': integer(196608),
  '.1.3.6.1.2.1.25.3.2.1.1.196609': integer(196609),
  '.1.3.6.1.2.1.25.3.2.1.1.196610': integer(196610),
  '.1.3.6.1.2.1.25.3.2.1.1.196611': integer(196611),
  '.1.3.6.1.2.1.25.3.2.1.1.262145': integer(262145),
  '.1.3.6.1.2.1.25.3.2.1.1.262146': integer(262146),
  '.1.3.6.1.2.1.25.3.2.1.1.262147': integer(262147),
  '.1.3.6.1.2.1.25.3.2.1.1.786432': integer(786432),

  '.1.3.6.1.4.1.2021.9.1.1.1': integer(1),
  '.1.3.6.1.4.1.2021.9.1.2.1': octet_string('/'),
  '.1.3.6.1.4.1.2021.9.1.3.1': octet_string('/dev/sda2'),
  '.1.3.6.1.4.1.2021.9.1.4.1': integer(-1),
  '.1.3.6.1.4.1.2021.9.1.5.1': integer(10),
  '.1.3.6.1.4.1.2021.9.1.6.1': integer(40970464),
  '.1.3.6.1.4.1.2021.9.1.7.1': integer(23622920),
  '.1.3.6.1.4.1.2021.9.1.8.1': integer(15234164),
  '.1.3.6.1.4.1.2021.9.1.9.1': integer(37),
  '.1.3.6.1.4.1.2021.9.1.10.1': integer(6),
  '.1.3.6.1.4.1.2021.9.1.11.1': integer(40970464),
  '.1.3.6.1.4.1.2021.9.1.12.1': integer(0),
  '.1.3.6.1.4.1.2021.9.1.13.1': integer(23622920),
  '.1.3.6.1.4.1.2021.9.1.14.1': integer(0),
  '.1.3.6.1.4.1.2021.9.1.15.1': integer(15234164),
  '.1.3.6.1.4.1.2021.9.1.16.1': integer(0),
  '.1.3.6.1.4.1.2021.9.1.100.1': integer(0),
  '.1.3.6.1.4.1.2021.9.1.101.1': octet_string(''),
  '.1.3.6.1.4.1.2021.10.1.1.1': integer(1),
### END CONF


The output of the debug is truncated

### DEBUG
....
[DEBUG] Received 43 bytes from ('127.0.0.1', 39738)
[DEBUG] ASN1_SEQUENCE: length = 41
[DEBUG] ASN1_INTEGER: 1
[DEBUG] ASN1_OCTET_STRING: public
[DEBUG] ASN1_GET_BULK_REQUEST_PDU: length = 28
[DEBUG] ASN1_INTEGER: 1324480461
[DEBUG] ASN1_INTEGER: 0
[DEBUG] ASN1_INTEGER: 10
[DEBUG] ASN1_SEQUENCE: length = 14
[DEBUG] ASN1_SEQUENCE: length = 12
[DEBUG] ASN1_OBJECT_IDENTIFIER: 1.3.6.1.2.1.25.2.3
[DEBUG] ASN1_NULL: 0
[DEBUG] max_repetitions: 10
[INFO] Crafting response
[INFO] 1324480461
[DEBUG] Sending 287 bytes of response
[DEBUG]
[DEBUG] Received 43 bytes from ('127.0.0.1', 39738)
[DEBUG] ASN1_SEQUENCE: length = 41
[DEBUG] ASN1_INTEGER: 1
[DEBUG] ASN1_OCTET_STRING: public
[DEBUG] ASN1_GET_BULK_REQUEST_PDU: length = 28
[DEBUG] ASN1_INTEGER: 1324480462
[DEBUG] ASN1_INTEGER: 0
[DEBUG] ASN1_INTEGER: 10
[DEBUG] ASN1_SEQUENCE: length = 14
[DEBUG] ASN1_SEQUENCE: length = 12
[DEBUG] ASN1_OBJECT_IDENTIFIER: 1.3.6.1.2.1.25.2.3
[DEBUG] ASN1_NULL: 0
[DEBUG] max_repetitions: 10
[INFO] Crafting response
[INFO] 1324480462
[DEBUG] Sending 287 bytes of response
[DEBUG]
[DEBUG] Received 43 bytes from ('127.0.0.1', 39738)
[DEBUG] ASN1_SEQUENCE: length = 41
[DEBUG] ASN1_INTEGER: 1
[DEBUG] ASN1_OCTET_STRING: public
[DEBUG] ASN1_GET_BULK_REQUEST_PDU: length = 28
[DEBUG] ASN1_INTEGER: 1324480463
[DEBUG] ASN1_INTEGER: 0
[DEBUG] ASN1_INTEGER: 10
[DEBUG] ASN1_SEQUENCE: length = 14
[DEBUG] ASN1_SEQUENCE: length = 12
[DEBUG] ASN1_OBJECT_IDENTIFIER: 1.3.6.1.2.1.25.2.3
[DEBUG] ASN1_NULL: 0
[DEBUG] max_repetitions: 10
[INFO] Crafting response
[INFO] 1324480463
[DEBUG] Sending 287 bytes of response
[DEBUG]
[DEBUG] Received 43 bytes from ('127.0.0.1', 39738)
[DEBUG] ASN1_SEQUENCE: length = 41
[DEBUG] ASN1_INTEGER: 1
[DEBUG] ASN1_OCTET_STRING: public
[DEBUG] ASN1_GET_BULK_REQUEST_PDU: length = 28
[DEBUG] ASN1_INTEGER: 1324480464
[DEBUG] ASN1_INTEGER: 0
[DEBUG] ASN1_INTEGER: 10
[DEBUG] ASN1_SEQUENCE: length = 14
[DEBUG] ASN1_SEQUENCE: length = 12
[DEBUG] ASN1_OBJECT_IDENTIFIER: 1.3.6.1.2.1.25.2.3
[DEBUG] ASN1_NULL: 0
....


## END DEBUG

Good luck :)

**Comment by devuxnullux** [comment]
Hi @delimitry 

I'm facing another oddity, snmpwalk is working OK but snmpget is not, here is an example of a config

### Config
DATA = {
  '1.3.6.1.2.1.1.1.0': octet_string('Linux Ubuntu'),
  '1.3.6.1.2.1.1.2.0': object_identifier('.1.3.6.1.4.1.8072.3.2.10'),
  '.1.3.6.1.2.1.25.2.3.1.2.1': object_identifier('.1.3.6.1.2.1.25.2.1.2'),
  '.1.3.6.1.2.1.25.2.3.1.2.31': object_identifier('.1.3.6.1.2.1.25.2.1.4'),
  '.1.3.6.1.2.1.25.2.3.1.3.1': octet_string('Physical memory'),	# hrStorageDescr
  '.1.3.6.1.2.1.25.2.3.1.3.31': octet_string('/'),
  '.1.3.6.1.2.1.25.2.3.1.4.1': integer(1024),	# hrStorageAllocationUnits
  '.1.3.6.1.2.1.25.2.3.1.4.31': integer(1024),
  '.1.3.6.1.2.1.25.2.3.1.5.1': integer(1*1024*1024),	# hrStorageSize
  '.1.3.6.1.2.1.25.2.3.1.5.31': integer(32*1024*1024),
  '.1.3.6.1.2.1.25.2.3.1.6.1': integer(1*1024*1024),		# hrStorageUsed
  '.1.3.6.1.2.1.25.2.3.1.6.31': integer(512*1024),
}
### End config

when I test with snmpwalk : snmpwalk -v 1 -c d 127.0.0.1:1610 iso
I get this expected output :
iso.3.6.1.2.1.1.1.0 = STRING: "Linux Ubuntu"
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.8072.3.2.10
iso.3.6.1.2.1.25.2.3.1.2.1 = OID: iso.3.6.1.2.1.25.2.1.2
iso.3.6.1.2.1.25.2.3.1.2.31 = OID: iso.3.6.1.2.1.25.2.1.4
iso.3.6.1.2.1.25.2.3.1.3.1 = STRING: "Physical memory"
iso.3.6.1.2.1.25.2.3.1.3.31 = STRING: "/"
iso.3.6.1.2.1.25.2.3.1.4.1 = INTEGER: 1024
iso.3.6.1.2.1.25.2.3.1.4.31 = INTEGER: 1024
iso.3.6.1.2.1.25.2.3.1.5.1 = INTEGER: 1048576
iso.3.6.1.2.1.25.2.3.1.5.31 = INTEGER: 33554432
iso.3.6.1.2.1.25.2.3.1.6.1 = INTEGER: 1048576
iso.3.6.1.2.1.25.2.3.1.6.31 = INTEGER: 524288

If I snmpget other than the two first OIDs I got this

snmpget -v 1 -c d 127.0.0.1:1610 iso.3.6.1.2.1.25.2.3.1.2.1
iso.3.6.1.2.1.25.2.3.1.2.1 = No Such Instance currently exists at this OID

snmpget -v 1 -c d 127.0.0.1:1610 iso.3.6.1.2.1.25.2.3.1.5.1
iso.3.6.1.2.1.25.2.3.1.5.1 = No Such Instance currently exists at this OID

snmpget -v 1 -c d 127.0.0.1:1610 iso.3.6.1.2.1.25.2.3.1.6.1
iso.3.6.1.2.1.25.2.3.1.6.1 = No Such Instance currently exists at this OID


And the two first OIDs are working as expected

snmpget -v 1 -c d 127.0.0.1:1610 iso.3.6.1.2.1.1.1.0
iso.3.6.1.2.1.1.1.0 = STRING: "Linux Ubuntu"

snmpget -v 1 -c d 127.0.0.1:1610 iso.3.6.1.2.1.1.2.0
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.8072.3.2.10

Best regards

**Comment by delimitry** [comment]
Hi @devuxnullux! 
`snmpget` got `No Such Instance currently exists at this OID` because the server cannot find the OID among the OIDs from config.  
So solve this please use all OIDs started with number ("1"), not with dot (".") in your config:
```
DATA = {
  '1.3.6.1.2.1.1.1.0': octet_string('Linux Ubuntu'),
  '1.3.6.1.2.1.1.2.0': object_identifier('.1.3.6.1.4.1.8072.3.2.10'),
  '1.3.6.1.2.1.25.2.3.1.2.1': object_identifier('.1.3.6.1.2.1.25.2.1.2'),
  '1.3.6.1.2.1.25.2.3.1.2.31': object_identifier('.1.3.6.1.2.1.25.2.1.4'),
  '1.3.6.1.2.1.25.2.3.1.3.1': octet_string('Physical memory'),	# hrStorageDescr
  '1.3.6.1.2.1.25.2.3.1.3.31': octet_string('/'),
  '1.3.6.1.2.1.25.2.3.1.4.1': integer(1024),	# hrStorageAllocationUnits
  '1.3.6.1.2.1.25.2.3.1.4.31': integer(1024),
  '1.3.6.1.2.1.25.2.3.1.5.1': integer(1*1024*1024),	# hrStorageSize
  '1.3.6.1.2.1.25.2.3.1.5.31': integer(32*1024*1024),
  '1.3.6.1.2.1.25.2.3.1.6.1': integer(1*1024*1024),		# hrStorageUsed
  '1.3.6.1.2.1.25.2.3.1.6.31': integer(512*1024),
}  
```

**Comment by devuxnullux** [comment]
Hi @delimitry ,
I feel stupid not catching that, what a PEBKAC, sorry for that
working as expected ;)
BR
