### ISSUE TITLE
Wrong Value Lenght Returned when Setting an Integer

### ISSUE THREAD

**Issue by r0bc94** [delimitry/snmp-server#44]
Hi, 

in your script, I have a configuration which basically registers a simple integer value on a given OID: 
```
DATA = {
    '1.3.6.1.2.1.1.7.0': integer(6)
}
```

however, when trying to query the oid from tools such as Paseller SNMP - Tester, the tool does not seem to understand the returned value. When capturing the traffic using wireshark, I see that wireshark complains about the value length: 

![image](https://github.com/user-attachments/assets/238b9658-8a46-415f-894b-8d221377fd59)

I'm wondering if there is something wrong in my configuration.

**Comment by delimitry** [comment]
Hi @r0bc94 I've fixed packing integers into 4 bytes instead of 8 bytes in the branch [fix_wrong_integer_length](https://github.com/delimitry/snmp-server/tree/fix_wrong_integer_length). 
Could you please check if your tools are working correctly now?
Thank you!

**Comment by r0bc94** [comment]
Hi @delimitry , 
thank you for coming back to me. I've tested the version provided in the given branch and it worked for me.
